services:
  express-api:
    build:
      context: ./app
    ports:
      - "8080:8080"

  locust:
    build:
      context: ./locust_tests
    ports:
      - "8089:8089" # Locust web interface
    depends_on:
      - express-api
    command: locust
